### ISSUE TITLE
Data should point to TLE used for aqcuisition

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-network#174]
Every time we store data we should point to the TLE used for the calculations. This is tremendously useful for debugging and post processing of data.

**Comment by comzeradd** [comment]
The TLE used for calculating the observation windows is not necessarily the same used for the actual observation from the client. This is due to the fact that client updates TLEs on every polling.

So the client should probably be responsible for posting the TLE used along with the recorded data. So this issue will track the necessary additions on the API to accommodate this along with any UI enhancements.
