### ISSUE TITLE
Send observation number to client

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-network#181]
Currently we send the payload ID to the client, which will differ from the observation ID.  We should send the observation ID in addition to the payload ID, that way the observation ID can be used to easily link back to the queued observations from within the client dashboard.

**Comment by comzeradd** [comment]
Since 804263b2c514e995a3cba30819f4184b766d65ca we have a permalink to Data elements based on their ID, so I think that's sufficient for linking back to the Network through client's web dashboard.

I also open a [PR](https://github.com/satnogs/satnogs-network/pull/257) that makes the permalink visible. Do you think we should open an issue on satnogs-client to track this?
