### ISSUE TITLE
Observations page takes too long to load

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-network#315]
![obs_page](https://cloud.githubusercontent.com/assets/498592/23166097/d86353ac-f847-11e6-9bdf-8c9c9f4b0724.png)

~8sec to get a response from the server. We should re-consider how we serve the page.

**Comment by faulteh** [comment]
- Currently filtering by property which can't be done by SQL so the python is slowing it down
- Change the query to prefetch the datas at the time of the main query
- Since the resultset is not likely to change extremely often but the result set will grow over time might look at caching the result for 5-10 minutes and/or until it's stale (cache max obs id > db max obs id) for the default case of 'no filtering'

If you assign it to me I'll take a look at it this evening and tomorrow.

**Comment by ppapadeas** [comment]
@faulteh good thoughts. Feel free to take this over and see where we can get. On caching I would be cautious as we may want to have kinda live results on the observations page. A smaller interval might be better. (or even celery it out?)
